# Generated by Django 2.2.7 on 2019-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=60)),
                ('uri', models.CharField(max_length=60)),
            ],
        ),
    ]
