# Generated by Django 2.2.7 on 2019-12-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
    ]
