# Generated by Django 2.2.7 on 2019-12-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0002_auto_20191201_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='uri',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uri', models.CharField(max_length=200)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marvelapi.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uri', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=80)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marvelapi.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uri', models.CharField(max_length=200)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marvelapi.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uri', models.CharField(max_length=200)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marvelapi.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uri', models.CharField(max_length=200)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marvelapi.Character')),
            ],
        ),
    ]
