# Generated by Django 2.2.7 on 2019-12-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapi', '0003_auto_20191201_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storie',
            old_name='tipo',
            new_name='type',
        ),
    ]
